### PR TITLE
some new features and clean code

### PR DESCRIPTION
**Pull request by biancode**
see the logs, please ...

### CODE REVIEW

**Comment by jayharper** [comment]
Hi Klaus!  Thanks for contributing.  I am super swamped at work and hope to get around testing your new code this week before pulling your updates into the repo.

**Comment by jayharper** [comment]
Got sometime today to look at your code.  You have put a lot of effort into this, so thanks.  Two things that I would like to see changed:

1.  Instead of the node status text reading "active reading" I prefer the Poll rate.  I prefer this because it is nice to be able to look at my flows and know what rate each node is polling at without having to double click the node.  

2.  The names of the new nodes are now to long to fit inside the node in the node palette.  

I will continue to look over the code and test but those were my very quick observations.

**Comment by biancode** [comment]
Ok, I'll change this and send a new request. Did you see the state with with the new response node and the two outputs of read and write, to be able to read the response by other nodes?Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [Argonne-National-Laboratory/node-red-contrib-modbustcp] some new features and clean code (#3)Von: "Jason D. Harper" An: Argonne-National-Laboratory/node-red-contrib-modbustcp Cc: Klaus Landsdorf Got sometime today to look at your code.  You have put a lot of effort into this, so thanks.  Two things that I would like to see changed:


Instead of the node status text reading "active reading" I prefer the Poll rate.  I prefer this because it is nice to be able to look at my flows and know what rate each node is polling at without having to double click the node.  
The names of the new nodes are now to long to fit inside the node in the node palette.  


I will continue to look over the code and test but those were my very quick observations.

**Comment by biancode** [comment]
here it is …

- time rate and its unit is now integrated in status
- the names of nodes should fit the range of the node-size

The new response node give the possibility to use response in other nodes.






Bianco Royal
Klaus Landsdorf
klaus.landsdorf@bianco-royal.de
http://bianco-royal.de/ <http://bianco-royal.de/>
http://contact.bianco-royal.de/ <http://contact.bianco-royal.de/>

**Pull request closed without merging**
